$schema: https://azuremlschemas.azureedge.net/promptflow/latest/AzureOpenAIConnection.schema.json
name: "inf-ai183709168106_aoai"
type: azure_open_ai
api_key: "" 
api_base: ""
api_type: "azure"
api_version: "2024-02-01"
auth_mode: key 


